export const characters = [
  {
    Name: 'Naruto',
    Age: 13,
    Village: 'Leaf',
    KekkeiGenkai: false,
    Speciality: 'ninjutsu',
    Info: "Naruto Uzumaki is a shinobi of Konohagakure's Uzumaki clan. He became the jinchūriki of the Nine-Tails on the day of his birth — a fate that caused him to be shunned by most of Konoha throughout his childhood. After joining Team Kakashi, Naruto worked hard to gain the village's acknowledgement all the while chasing his dream to become Hokage.",
    id: 0,
  },
  {
    Name: 'Sasuke',
    Age: 13,
    Village: 'Leaf',
    KekkeiGenkai: true,
    Speciality: 'genjutsu',
    Info: "Sasuke Uchiha is one of the last surviving members of Konohagakure's Uchiha clan. After his older brother, Itachi, slaughtered their clan, Sasuke made it his mission in life to avenge them by killing Itachi. He is added to Team 7 upon becoming a ninja and, through competition with his rival and best friend, Naruto Uzumaki, Sasuke starts developing his skills.",
    id: 1,
  },
  {
    Name: 'Sakura',
    Age: 13,
    Village: 'Leaf',
    KekkeiGenkai: false,
    Speciality: 'taijutsu',
    Info: "Sakura is a kunoichi of Konohagakure. When assigned to Team 7, Sakura quickly finds herself ill-prepared for the duties of a shinobi. However, after training under the Sannin Tsunade, she overcomes this, and becomes recognised as one of the greatest medical-nin in the world.",
    id: 2,
  },
  {
    Name: 'Kakashi',
    Age: 27,
    Village: 'Leaf',
    KekkeiGenkai: true,
    Speciality: 'ninjutsu',
    Info: "Kakashi Hatake is a shinobi of Konohagakure's Hatake clan. Famed as Kakashi of the Sharingan, he is one of Konoha's most talented ninja, regularly looked to for advice and leadership despite his personal dislike of responsibility. To his students on Team 7, Kakashi emphasises the importance of teamwork; he himself received this lesson, along with the Sharingan, from his childhood friend, Obito Uchiha.",
    id: 3,
  },
  {
    Name: 'Jiraiya',
    Age: 50,
    Village: 'Leaf',
    KekkeiGenkai: false,
    Speciality: 'ninjutsu',
    Info: "Jiraiya was one of Konohagakure's Sannin. Famed as a hermit and pervert of stupendous ninja skill, Jiraiya travelled the world in search of knowledge that would help his friends, the various novels he wrote, and, posthumously, the world in its entirety - knowledge that would be passed on to his godson and final student, Naruto Uzumaki.",
    id: 4,
  },
  {
    Name: 'Rock Lee',
    Age: 14,
    Village: 'Leaf',
    KekkeiGenkai: false,
    Speciality: 'taijutsu',
    Info: "Rock Lee is a shinobi of Konohagakure's Lee clan and a member of Team Guy. Unlike most shinobi, he lacked the skills necessary to use ninjutsu or genjutsu. However, he overcomes those shortcomings by undergoing special training from Might Guy that would make him a taijutsu master while still a genin.",
    id: 5,
  },
  {
    Name: 'Kiba',
    Age: 13,
    Village: 'Leaf',
    KekkeiGenkai: false,
    Speciality: 'taijutsu',
    Info: "Kiba Inuzuka is a member of Konohagakure's Inuzuka clan and a member of Team Kurenai. Despite his headstrong, and at times egotistic attitude, Kiba is loyal to his comrades and will do anything to protect them with his trusted canine companion, Akamaru, by his side.",
    id: 6,
  },
  {
    Name: 'Neji',
    Age: 14,
    Village: 'Leaf',
    KekkeiGenkai: true,
    Speciality: 'taijutsu',
    Info: "Neji Hyūga was a shinobi of Konohagakure's Hyūga clan. Though a prodigy even by the Hyūga's standards, Neji was a member of the clan's branch house; no matter how skilled he became, he would always be in service to the Hyūga's main house, a fact that convinced him fate was predetermined.",
    id: 7,
  },
  {
    Name: 'Shikamaru',
    Age: 13,
    Village: 'Leaf',
    KekkeiGenkai: false,
    Speciality: 'ninjutsu',
    Info: "Shikamaru Nara is a shinobi of Konohagakure's Nara clan. Though lazy by nature, Shikamaru has a rare intellect that consistently allows him to prevail in combat. The responsibilities that these successes leave him with cause him frequent annoyance, but he gladly accepts them so that he may be of service to his fellow members of Team Asuma, and to prove himself to generations of the past and future.",
    id: 8,
  },
  {
    Name: 'Choji',
    Age: 13,
    Village: 'Leaf',
    KekkeiGenkai: false,
    Speciality: 'taijutsu',
    Info: "Chōji Akimichi is a member of Konohagakure's Akimichi Clan. Though sensitive about his weight, Chōji is nevertheless dedicated to his friends, especially in Team Asuma.",
    id: 9,
  },
  {
    Name: 'Kimimaro',
    Age: 15,
    Village: 'Sound',
    KekkeiGenkai: true,
    Speciality: 'taijutsu',
    Info: "Kimimaro was the sole survivor of the Kaguya clan. Upon dedicating his life to Orochimaru, he became the leader of the formerly-named Sound Five, until he fell ill, which forced him to leave the group. Unlike the rest of his clan, Kimimaro didn't have a particular interest in fighting or killing and saw his abilities only as a means to be of use to others.",
    id: 10,
  },
  {
    Name: 'Sakon & Ukon',
    Age: 14,
    Village: 'Sound',
    KekkeiGenkai: true,
    Speciality: 'taijutsu',
    Info: "Sakon and his older brother Ukon were twin brothers from Otogakure and the apparent leader(s) of the Sound Four. Described as spiteful and confident, Sakon enjoyed fighting and liked bad-mouthing the opposition. When in battle, Sakon liked to prolong the fight by toying with the opponent and using unnecessarily powerful techniques to show off.",
    id: 11,
  },
  {
    Name: 'Kidomaru',
    Age: 14,
    Village: 'Sound',
    KekkeiGenkai: false,
    Speciality: 'taijutsu',
    Info: "Kidōmaru was a shinobi from Otogakure and a member of the Sound Four. He generally saw a battle as a game, and displayed a laid-back ease in fights. Kidōmaru greatly enjoyed combat and relished in strong opponents as a source of entertainment, finding weaker opponents not worth his time and boring.",
    id: 12,
  },
  {
    Name: 'Tayuya',
    Age: 14,
    Village: 'Sound',
    KekkeiGenkai: false,
    Speciality: 'genjutsu',
    Info: "Tayuya was a kunoichi of Otogakure and a member of the Sound Four. While occasionally very quiet, Tayuya was an overbearing and abrasive, sharp-tongued individual. She was very blunt and foul-mouthed towards most people, even towards her teammates, though they were apparently used to her behaviour and usually responsed with nothing more than slight irritation when insulted.",
    id: 13,
  },
  {
    Name: 'Jirobo',
    Age: 14,
    Village: 'Sound',
    KekkeiGenkai: false,
    Speciality: 'taijutsu',
    Info: "Jirōbō was a shinobi of Otogakure and a member of the Sound Four. Out of the Sound Four members, Jirōbō was usually the most calm, sensible, and silent member, as shown by his rigid demeanour. He was polite to his teammates, which puts him at odds with Tayuya as he dislikes it when she uses foul language or called him 'fatso'.",
    id: 14,
  },
  {
    Name: 'Gaara',
    Age: 13,
    Village: 'Sand',
    KekkeiGenkai: false,
    Speciality: 'ninjutsu',
    Info: "Gaara is a shinobi of Sunagakure. He was made the jinchūriki of the One-Tailed Shukaku before he was born, causing the villagers of Suna to fear him as a monster. With nobody to connect to, Gaara grew up hating the world and looking out only for himself, giving his life meaning by killing anyone he came across.",
    id: 15,
  },
  {
    Name: 'Kankuro',
    Age: 15,
    Village: 'Sand',
    KekkeiGenkai: false,
    Speciality: 'ninjutsu',
    Info: "Kankurō is a shinobi of Sunagakure and the second eldest of the Three Sand Siblings. While initially terrified of his younger brother, Kankurō would come to believe in him and his dream to become the Kazekage like their father before them and would become one of Gaara's most loyal protectors, confidant and bodyguard.",
    id: 16,
  },
  {
    Name: 'Temari',
    Age: 16,
    Village: 'Sand',
    KekkeiGenkai: false,
    Speciality: 'ninjutsu',
    Info: "Temari is a former kunoichi of Sunagakure's Kazekage clan. After marrying Shikamaru Nara, she becomes a member of the Nara clan and emigrates to Konohagakure, where she works as a kunoichi for the village. ",
    id: 17,
  },
  {
    Name: 'Orochimaru',
    Age: 50,
    Village: 'Sound',
    KekkeiGenkai: true,
    Speciality: 'ninjutsu',
    Info: "Orochimaru is one of Konohagakure's legendary Sannin. With a life-ambition to learn all of the world's secrets, Orochimaru seeks immortality so that he might live all of the lives necessary to accomplish his task. After being caught red-handed performing unethical experiments on his fellow citizens for the sake of this immortality, Orochimaru defected from Konoha and became a missing-nin.",
    id: 18,
  },
  {
    Name: 'Kabuto',
    Age: 20,
    Village: 'Sound',
    KekkeiGenkai: false,
    Speciality: 'ninjutsu',
    Info: "Kabuto Yakushi spent most of his life as a spy working for many different individuals, organisations, and countries. His natural talents in intelligence-gathering and medicine attracted the attention of Orochimaru when he was younger, who made Kabuto his right-hand man.",
    id: 19,
  },
]